### ISSUE TITLE
What's keeping autoequal from working with abstract classes?

### ISSUE THREAD

**Issue by wrbl606** [mrgnhnt96/autoequal#5]
When trying to generate the code for my abstract class, a severe error occurred:

```plain
[SEVERE] autoequal_gen:autoequal on .../counter_bloc.dart:

abstract class CounterEvent extends Equatable is abstract. Autoequal doesn't support abstract classes.
```

The target class:

```dart
@autoequalMixin
abstract class CounterEvent extends Equatable {
  const CounterEvent();
}
```

The error message is clear, but what's keeping `autoequal` from generating the code for abstract classes?

**Comment by SunnyDayDev** [comment]
The `equatable` lib overrides `==` so that compares instances by class type and `props`, so every inheritor of some abstract class will always be unequal to other.

If you ask, why can't mark some abstract class to be `autoequal` and generate `props` for each inheritor. I think, each inheritor must decide for himself whether it is `autoequal` or not. Otherwise, we get less control and the abstract class becomes just a "Marker Interface".

**Comment by wrbl606** [comment]
Thanks for your response!
